### ISSUE TITLE
having issues with configuration

### ISSUE THREAD

**Issue by turuncuoglu** [pdemarco925/homebridge-icomfort#10]
I am having hard time adding the config file.  I always get errors.  Is there an example I can look at.  Thanks

**Comment by pdemarco925** [comment]
What kind of errors are you getting? 
A full homebridge config with just this plugin would look like this.
{
    "bridge": {
        "name": "MyHomebridge",
        "username": "AA:AA:AA:AA:AA:AA",
        "port": 33333,
        "pin": "123-45-678"
    },
    "accessories": [
        {
            "accessory": "iComfortThermostat",
            "name": "Thermostat",
            "username": "USERNAME",
            "password": "PASSWORD",
            "gatewaySN": "SERIALNUMBER",
            "zoneNumber": 0
         }
     ]
}
