### ISSUE TITLE
home/away mode

### ISSUE THREAD

**Issue by stevesreed** [pdemarco925/homebridge-icomfort#2]
It would be really nice if we could put the iComfort in home/away mode, so it would work with the "I'm leaving" and "I'm Home" automations.

Eccobee seems to support "Away", "Sleep" and "Home" modes (https://support.ecobee.com/hc/en-us/articles/115007670867-Using-Apple-HomeKit-with-your-ecobee4) so there must be some setup in homekit for those to automatically be recognized.

**Comment by pdemarco925** [comment]
I'm really curious how they are doing it. The Apple defined characteristic for setting the heating / cooling state only defines OFF, COOL, HEAT or AUTO (see https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js around line 2341). Where I'm not really setting it to auto, I'm just setting it back to the last selected program schedule mode. 

Homebridge is based on the HAP-NodeJS implementation, and even though the true Apple Thermostat Service offers additional characteristics (https://developer.apple.com/documentation/homekit/hmservicetypethermostat) it's still not obvious to me how the Eccobee is doing the other settings, unless they are just doing artificially mappings.

You can set the thermostat mode to off in the i'm leaving scene and auto in the i'm home scene. And I do realize there is a big difference between off and away. 

I'll do some looking at the i-comfort project (what this project leverages to actually communicate with the thermostat) to see if the APIs he provides allows me to switch to/from away mode. If so, one hack would be to re-map Off to Away.

**Comment by stevesreed** [comment]
I think "off" is really just a seasonal command (set it off when summer starts if you don't have Air conditioner", etc.), so substituting away for off probably makes sense as a siri command.

**Comment by pdemarco925** [comment]
The i-comfort author added the new endpoint, and I was able to add a custom characteristic  / setting specifically for away mode. The only issue is that if you rely on Apple's Home app you don't get access to the characteristic. If you have one of the third party homekit apps that are more advanced (like Home - Smart Home Automation) it will allow you to access the away setting and add it to any scenes or triggers. This is the 'proper' way to deal with it, will that work for you?

**Comment by stevesreed** [comment]
Does it respond to siri? If it does not work with the home app it does that mean it cannot be part of an automation? Or just not one set up with the home app?

I have some others homeland apps so if I can set uptake automation there that would work.

The main goal is to set the system to away when running the "I'm leaving" automation, and turn it back on when running "I'm home"

**Comment by stevesreed** [comment]
BTW. I definitely owe you and the i-comfort project author a beer if you are ever in San Diego :)

**Comment by pdemarco925** [comment]
I'll publish the updates tomorrow and let you know when they are available. You can try it out then.
I'm pretty sure it is just definition/updates of the automation needs to be done in another app. They will appear in Home and the scene can be trigged in Home or by Siri.

**Comment by pdemarco925** [comment]
OK, I just published v1.0.0. It includes changes for both away mode support and zones. It has an updated dependency on v1.3.0 of the icomfort project, but npm should automatically take care of updating that as well.

**Comment by stevesreed** [comment]
Thanks again for adding that support. When I get a chance I’ll learn JavaScript and contribute when possible. I’ve been doing  C/C++ and HLSL for so long, I can’t make heads or tails of some of the JavaScript  :)

**Comment by stevesreed** [comment]
I have "Home - Smart Home Automation" app, but it does not show any away option for the thermostats.

Also siri says she can find a thermostat that supports away. Is there anything else I need to set up to get her to recognize the feature?
