### ISSUE TITLE
package.jsom file has old version?

### ISSUE THREAD

**Issue by stevesreed** [pdemarco925/homebridge-icomfort#3]
I update grade to 1.0.0 homebridge-icomfort looks like it still at version 0.0.1 in the home bridge config web interface. It looks like the package.json still has the old version number listed in it.

**Comment by pdemarco925** [comment]
how did you do the upgrade? I assume you restarted homebridge or the host it is on?
Can try just reinstalling 'npm install -g homebridge-icomfort'
i know for some reason npm update doesn't always work for me all the time.
When you update did you see a bunch of uri requests then at the end (plus any updated dependencies):
/usr/lib
└── homebridge-icomfort@1.0.0 

The version published had the right package.json, just i uploaded the wrong file to git.
Also check to see if the icomfort node_module got updated to v1.3.0.

The away should just show up in the Home - Smart Home Automation app as a toggle, no setup required.

**Comment by stevesreed** [comment]
Strange. It looks like the mom update did not work and when I did the install last night it only got the iComfort node_module, but not the new homebridge-iComfort code. 

I re did it this morning and it did pick up homebridge-iComfort 1.0.0. It works with the 3rd party “home - smart home automation” app fine, but Siri still does not see any thermostat that supports away mode. 

I’ve added it to the leaving and arriving scenes via the home sma app. I did not get to try it yet, but I will tonight. Finger crossed.

**Comment by pdemarco925** [comment]
Ok, yeah, i'm just a hacking these projects together, not a real developer so I could have something wrong related to the npm/git setup. 

Yes, works with home-smart home automation. Siri won't recognize it. I really hope next iOS release adds better support for custom characteristics.

I didn't trying adding it to leaving / arriving scenes, but what I did do was create an AwayMode scene in home-sha. That new scene shows up in Apple Home.app and can be triggered in the app or by telling Siri to "Set AwayMode scene". 

Another option which I haven't explored, but I think is possible. There are a couple of dummy switch projects for homebridge (one example homebridge-dummy). You can then use the state change as a trigger for other automation/actions.
