### ISSUE TITLE
Add Circulate function to home app

### ISSUE THREAD

**Issue by AdrianCalifornia** [pdemarco925/homebridge-icomfort#4]
Would it be possible to add a circulate function to the home app?

**Comment by pdemarco925** [comment]
The Lenox APIs that are used by the icomfort-js project don't support that feature. Dan is looking at switching to the APIs used by the iComfort WiFi app, but not sure when he'll finish the port. 

Even if the API existed, the function wouldn't be supported in Apple's Home.app. To my knowledge their app doesn't support custom characteristics (yet). You'd have to use a third party app. 

If/when Dan does the API port I'm going to be looking to leverage all available settings through custom characteristics.
