### ISSUE TITLE
home bridge errors when in away mode

### ISSUE THREAD

**Issue by stevesreed** [pdemarco925/homebridge-icomfort#5]
Every once in a while, Homebridge stops responding to Homekit, and all my devices would say "not responding" in the Home app.

I recently tracked this down be occurring when my iComfort thermostat is in away mode. 

It appears to throw errors when in away mode, and when it's doing that Homebridge no longer responds to Homekit. as soon as I take the comfort out of away mode, Homebridge updates the devices and they show their current status in the home app.

The errors are the following:

Sep 03 07:57:55 raspberrypi homebridge[544]: (node:544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Operation_Mode' of 
Sep 03 07:57:55 raspberrypi homebridge[544]: at icomfort.getThermostatInfoList.then.res (/usr/lib/node_modules/homebridge-icomfort/index.js:13
Sep 03 07:57:55 raspberrypi homebridge[544]: at <anonymous>
Sep 03 07:57:55 raspberrypi homebridge[544]: at process._tickCallback (internal/process/next_tick.js:160:7)
Sep 03 07:57:55 raspberrypi homebridge[544]: (node:544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated e
Sep 03 07:57:55 raspberrypi homebridge[544]: (node:544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the futu
Sep 03 07:57:55 raspberrypi homebridge[544]: (node:544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Cool_Set_Point' of 
Sep 03 07:57:55 raspberrypi homebridge[544]: at icomfort.getThermostatInfoList.then.res (/usr/lib/node_modules/homebridge-icomfort/index.js:27
Sep 03 07:57:55 raspberrypi homebridge[544]: at <anonymous>
Sep 03 07:57:55 raspberrypi homebridge[544]: at process._tickCallback (internal/process/next_tick.js:160:7)
Sep 03 07:57:55 raspberrypi homebridge[544]: (node:544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated e
Sep 03 07:57:55 raspberrypi homebridge[544]: (node:544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Heat_Set_Point' of 
Sep 03 07:57:55 raspberrypi homebridge[544]: at icomfort.getThermostatInfoList.then.res (/usr/lib/node_modules/homebridge-icomfort/index.js:30
Sep 03 07:57:55 raspberrypi homebridge[544]: at <anonymous>
Sep 03 07:57:55 raspberrypi homebridge[544]: at process._tickCallback (internal/process/next_tick.js:160:7)
Sep 03 07:57:55 raspberrypi homebridge[544]: (node:544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated e
Sep 03 07:57:55 raspberrypi homebridge[544]: (node:544) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'System_Status' of u
Sep 03 07:57:55 raspberrypi homebridge[544]: at icomfort.getThermostatInfoList.then.res (/usr/lib/node_modules/homebridge-icomfort/index.js:12
Sep 03 07:57:55 raspberrypi homebridge[544]: at <anonymous>

**Comment by pdemarco925** [comment]
Interesting. I might actually need to learn javascript a bit to fix this, rather than just hacking away. I've been avoiding trying to figure out what promises are and how to deal with them. :)

Just curious, are you using any automation / triggers that leverage the thermostat? Just trying to find a way to recreate it here.

**Comment by stevesreed** [comment]
Currently it’s not in any automations. I had to rebuild my home and have not reset up most of the automation yet. 

To repo it all I need to do it enable away from the thermostat or the official Lennox iPhone app.

**Comment by mbroderick** [comment]
I get these errors just from adding them to my Home app on an iPad, and now get no updates from Homebridge as it seems hung/dead whenever I launch with this plugin enabled after pairing it. Let me know if there's anything you want me to try doing
