### ISSUE TITLE
zoneNumber

### ISSUE THREAD

**Issue by ac4lt** [pdemarco925/homebridge-icomfort#6]
We have two zones and per the readme, I tried adding then in with "zoneNumber": 0 and "zoneNumber": 1. However, this caused all sorts of errors. Just to see what happened, I tried removing the zoneNumber parameter from both accessory definitions and it appears to be working. I'm not sure what the issue is with the zoneNumber parameter but I wanted to let you know. It might just be a documentation issue.

I'm looking forward to trying this out. I've been wanting to have our system HomeKit accessible for a long time and this looks very encouraging!

**Comment by pdemarco925** [comment]
Sorry, life has been crazy....

In order to setup it up for multiple zones you need two definitions in your config file.

  {
    "accessory": "iComfortThermostat",
    "name": "Thermostat-zone1",
    "username": "USERNAME",
    "password": "PASSWORD",
    "gatewaySN": "SERIAL_NUMBER",
    "zoneNumber": 0
  },
  {
    "accessory": "iComfortThermostat",
    "name": "Thermostat-zone2",
    "username": "USERNAME",
    "password": "PASSWORD",
    "gatewaySN": "SERIAL_NUMBER",
    "zoneNumber": 1
  }

**Comment by pdemarco925** [comment]
no response, assume it works.
