### ISSUE TITLE
iComfort S30 supported?

### ISSUE THREAD

**Issue by GaryOkie** [pdemarco925/homebridge-icomfort#8]
Please confirm if this plugin supports the Lennox iComfort S30 thermostat or just the iComfort Wifi model.   My understanding is the API's are different.

Thanks!

**Comment by pdemarco925** [comment]
I only have the iComfort WiFi, so I'm unable to test with other versions fo the thermostat. I just saw you posted to Dan's project as well. He understands the APIs a lot better. I'll try to watch for a reply from him and see if there is any updates on his side and if something should be updated on this project (and I can find time to do it).
Thanks

**Comment by GaryOkie** [comment]
Thanks very much for the reply.   We'll both be watching for Dan's reply  :)
