### ISSUE TITLE
How do I figure out my Gateway SN? 

### ISSUE THREAD

**Issue by eklipz09** [pdemarco925/homebridge-icomfort#9]
I am thinking its the Thermostat SN, and it does not seem to work, I keep getting a 401.

**Comment by pdemarco925** [comment]
If you go to https://www.myicomfort.com/Dashboard.aspx and under the System tab, it is the Serial Number associated with the Thermostat. Not sure if it is case sensitive or not, but I have it in capital letters just like it appears on the website... (e.g. CB28B32718.
You can try running the test scripts from the API used behind the scenes for interfacing with Lennox's servers (https://github.com/deHugo/icomfort-js). It's a little more stand alone and will reduce the number of variables involved (just the API and Lennox server vs all of the Homebridge and HomeKit stuff too).
